/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.wuespace.telestion.tool.connector.serial[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
