/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.wuespace.telestion.tool.connector.serial;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
}
