# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Unzip distribution
      run: tar -xvf build/distributions/telestion-serial-connector.tar -C build/distributions
    - name: Build executable
      run: |
        mkdir build/executable && \
        cd build/executable && \
        jpackage \
          --input ../distributions/telestion-serial-connector/lib \
          --name telestion-serial-connector \
          --main-class de.wuespace.telestion.tool.connector.serial.App \
          --main-jar telestion-serial-connector.jar \
          --type deb \
        && ls -R 
    - name: Upload artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: telestion-serial-connector.deb
        path: build/executable/telestion-serial-connector*.deb
        retention-days: 7
      
